In [1]:
import TestLLM

In [2]:
TestLLM.print_correctly_classified_instances(0, "POS" , "BERTic")

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.2.0.dev20230928)
    Python  3.11.5 (you have 3.11.4)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details


105     koji oseća ili ispoljava veliko uzbuđenje ili ...
184     osećanje naklonosti prema nekome ili nećemu do...
688          okarakterisan prijateljstvom i dobrom voljom
867                            koji čini ili donosi dobro
915                 na visokom nivou po rangu ili značaju
1051             koji ohrabruje, odobrava ili zadovoljava
1154                                 Biti veoma primetan.
1168            koji inavodi na divljenje ili odobravanje
1190    Pozitivan ili negativan kvalitet nečega što ga...
1281                  osećanje prijateljstva i uvažavanja
1525              revnostan u posvećenosti i privrženosti
2085                             koji donosi dobar profit
2344    Koji koristi intelekt ili je privlačan intelektu.
2559           koji ispoljava pogodan ili povoljan uticaj
2680                                  biti privlačan kome
2682              onaj koji ima visoku vrednost ili cenu;
2752                        Biti zdrav, osećati se dobro.
2835          

In [3]:
TestLLM.print_correctly_classified_instances(0, "POS" , "BERTicovo")

184     osećanje naklonosti prema nekome ili nećemu do...
1168            koji inavodi na divljenje ili odobravanje
1190    Pozitivan ili negativan kvalitet nečega što ga...
1281                  osećanje prijateljstva i uvažavanja
1525              revnostan u posvećenosti i privrženosti
3043                     osećati zadovoljstvo zbog nečega
3115                                   moralna ispravnost
3235    Kvalitet koji čini daa je nešto poželjno, vred...
3921    osećati se veselo i biti ispunjen dobrim raspo...
Name: X, dtype: object


In [4]:
TestLLM.print_correctly_classified_instances(2, "POS" , "BERTic")

5                          Stav divljenja ili poštovanja.
63                         osoba koja voli ili je voljena
74                          Biti prihvatljiv ili pristao.
923            koji oseća ili pokazuje dobro raspoloženje
1019                           Korisna ili vredna osobina
1128    Ličnost koja može da proceni vrednost ili kval...
1218                               Stanje izuzetne sreće.
1232                Stanje zadovoljstva jer nema bolesti.
1323                 ono što je dobro, vredno ili korisno
1584                   postojan u naklonosti ili odanosti
1590    Onaj koji uživa ili pokazuje radost, zadovoljs...
1682                činjenje dobra; osećaj dobrotvornosti
1774                   osećaj spontano dobrog rapoloženja
2301    kvalitet koji ima nešto što ima veliku vrednos...
2305    imati poželjne ili pozitivne kvalitete, posebn...
2884       koji je sklon ljubavi ili ispoljavanju ljubavi
2947                                       veseo i ozaren
3082    Stanje

In [5]:
TestLLM.print_correctly_classified_instances(2, "POS" , "BERTicovo")

5                          Stav divljenja ili poštovanja.
63                         osoba koja voli ili je voljena
74                          Biti prihvatljiv ili pristao.
923            koji oseća ili pokazuje dobro raspoloženje
1019                           Korisna ili vredna osobina
1218                               Stanje izuzetne sreće.
1232                Stanje zadovoljstva jer nema bolesti.
1323                 ono što je dobro, vredno ili korisno
1584                   postojan u naklonosti ili odanosti
1590    Onaj koji uživa ili pokazuje radost, zadovoljs...
1682                činjenje dobra; osećaj dobrotvornosti
1714                                      Upadljiv uspeh.
1774                   osećaj spontano dobrog rapoloženja
2301    kvalitet koji ima nešto što ima veliku vrednos...
2305    imati poželjne ili pozitivne kvalitete, posebn...
2571    kvalitet da čovek ne stavlja sebe prvo, već da...
2756                   kvalitet onoga što ima veliku cenu
2871    osobin

In [6]:
TestLLM.print_correctly_classified_instances(4, "POS" , "BERTic")

208            radnja koju karakteriše dobro raspoloženje
258                koji zaslužuje uvažavanje i poštovanje
638                            Izuzetna moralna vrednost.
1080                                       veseo i ozaren
1304    osobina ljudi da veruju u poštenje i pouzdanos...
1644        osobina prefinjene uglađenosti i dobrog ukusa
1768                onaj koji poseduje moralne kvalitete;
1901                  osećanje duboke ljubavi i divljenja
2094    Onaj koji uživa ili pokazuje radost, zadovoljs...
2154           Nalaziti da je nešto zabavno ili prijatno.
2164                                        osećati sreću
2322    osećati se veselo i biti ispunjen dobrim raspo...
2355    Kvalitet koji čini daa je nešto poželjno, vred...
2405                   kvalitet onoga što ima veliku cenu
2555                                 koji nešto potvrđuje
2710                         koji čini živahnim i veselim
3164    Prijatan za oči ili dušu, posebno jer je lep i...
3220          

In [7]:
TestLLM.print_correctly_classified_instances(4, "POS" , "BERTicovo")

51      Koji ima potrebne sposobnosti, veštinu ili zna...
208            radnja koju karakteriše dobro raspoloženje
258                koji zaslužuje uvažavanje i poštovanje
277     Proceniti da je nešto dobro; misliti pozitivno...
568     Koji proizvodi ili je sposoban da proizvede na...
638                            Izuzetna moralna vrednost.
817     sposobnost postojanja ili delovanja u harmonič...
1076                              Visoka vrednost nečega.
1080                                       veseo i ozaren
1644        osobina prefinjene uglađenosti i dobrog ukusa
1759    Osećanja proživljena kada je neko u zadovoljno...
1768                onaj koji poseduje moralne kvalitete;
1901                  osećanje duboke ljubavi i divljenja
2094    Onaj koji uživa ili pokazuje radost, zadovoljs...
2164                                        osećati sreću
2322    osećati se veselo i biti ispunjen dobrim raspo...
2355    Kvalitet koji čini daa je nešto poželjno, vred...
2405          

In [8]:
TestLLM.compare_models(0, "POS", "BERTic", "BERTicovo")

Texts correctly classified as class 1 by both models:
 0    osećanje naklonosti prema nekome ili nećemu do...
1            koji inavodi na divljenje ili odobravanje
2    Pozitivan ili negativan kvalitet nečega što ga...
3                  osećanje prijateljstva i uvažavanja
4              revnostan u posvećenosti i privrženosti
5                     osećati zadovoljstvo zbog nečega
6                                   moralna ispravnost
7    Kvalitet koji čini daa je nešto poželjno, vred...
8    osećati se veselo i biti ispunjen dobrim raspo...
Name: X, dtype: object
Texts correctly classified as class 1 by the first model but not the second:
 105     koji oseća ili ispoljava veliko uzbuđenje ili ...
688          okarakterisan prijateljstvom i dobrom voljom
867                            koji čini ili donosi dobro
915                 na visokom nivou po rangu ili značaju
1051             koji ohrabruje, odobrava ili zadovoljava
1154                                 Biti veoma primetan.
2

In [9]:
TestLLM.compare_models(0, "NEG", "BERTic", "BERTicovo")

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [ ]:
TestLLM.compare_models(0, "NEG", "BERTic", "SRGPT")

Texts correctly classified as class 1 by both models:
 0     Kvalitet nečega što nije adekvatno ili perfektno.
1             Posramiti nekoga; povrediti nečiji ponos.
2                       Kvalitet onog ko nije brižljiv.
3     koji zaslužuje sažaljenje ili podstiče na saža...
4                 nenormalna depresija i nezadovoljstvo
5     Stanje u kome čovek ne može da funkcioniše nor...
6     nejasno i neprijatno osećanje koje se ima u iš...
7               Smatrati da je nešto loše ili pogrešno.
8                       okrutno ili nehumano postupanje
9                           tuga izazvana bolom i tugom
10               žalostan zbog gubitka ili uskraćenosti
11                      Uzrok velikih patnji i nesreće.
12    Intenzivno ili preterano loš ili neprijatan po...
13    iznenadno stanje žestoke emocionalne uznemiren...
14    mentalno uznemiren zbog moguće nesreće ili opa...
15    koji je označen beznadežnošću ili ispoljava be...
16                    nedolično ili nemoralno pon

In [ ]:
TestLLM.print_correctly_classified_instances(2, "POS" , "SRGPT")

128                         Biti prihvatljiv ili pristao.
380            Osećanje samopoštovanja i lične vrednosti.
436              koji ohrabruje, odobrava ili zadovoljava
812     Kvalitet koji čini daa je nešto poželjno, vred...
1135            (za naglašavanje značenja) izuzetno dobro
2031            Biti nekome prihvatljiv ili odgovarajući.
2269               Osobina onoga što zaslužuje poverenje.
3176                               osećanje naklonjenosti
3471           radnja koju karakteriše dobro raspoloženje
4098                           koji čini ili donosi dobro
Name: X, dtype: object


In [ ]:
TestLLM.print_correctly_classified_instances(4, "POS" , "SRGPT")

76                    osećanje duboke ljubavi i divljenja
588     Koji može da čini po slobodnoj volji; koji nij...
982     gajiti osećanja dubokog poštovanja i straha pr...
1275    kvalitet nečega što je isto po količini, meri,...
1290    koji pokazuje ili je motivisan saosećanjem, ra...
1864                  osećanje prijateljstva i uvažavanja
2056    Osećanja proživljena kada je neko u zadovoljno...
2630           koji ispoljava pogodan ili povoljan uticaj
2857                           koji lako žali i sažaljeva
2879    Osećanje naklonjenosti drugim osobama; uživanj...
3179           Osećanje samopoštovanja i lične vrednosti.
3481                         koji čini živahnim i veselim
3611                        Biti zdrav, osećati se dobro.
3675    Onaj koji uživa ili pokazuje radost, zadovoljs...
3781                     osećati zadovoljstvo zbog nečega
4336    Stanje pozitivnih osećanja, od zadovoljstva do...
4509    osobina ljudi da veruju u poštenje i pouzdanos...
4649          

In [ ]:
TestLLM.print_correctly_classified_instances(4, "NEG" , "SRGPT")

109        Koji nije popustljiv, kojim se teško upravlja.
215                                         Osećati tugu.
437                           koji izaziva strah ili užas
512     škrtost koja proizilazi iz brige za sopstvenu ...
634                      Koji nije naklonjen prea nečemu.
635                    onaj koji nije stalan ili postojan
638                                      uzrokovati strah
778                      koji nije raspoložen da sarađuje
828        izuzetno uvredljiv za moral; koji izaziva užas
936                          Stanje u kome je neko tužan.
1391                Usmrtiti namerno i sa predumišljajem.
1688                      Ono što izaziva bol ili patnju.
1729                            povrediti nečija osećanja
1835          Kvalitet koji ne pruža zadovoljstvo čulima.
1846                 svojstvo onoga kome nedostaje živost
2418                     biti odbojan; izazivati averziju
2479    Slabljenje ili degeneracije, posebno usled nek...
2835          

In [ ]:
TestLLM.test_model(4, "POS", "SRGPT")

[[4921   25]
 [  54   18]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4946
           1       0.42      0.25      0.31        72

    accuracy                           0.98      5018
   macro avg       0.70      0.62      0.65      5018
weighted avg       0.98      0.98      0.98      5018



In [ ]:
TestLLM.test_model(4, "POS", "BERTic")

[[4933   13]
 [  47   25]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4946
           1       0.66      0.35      0.45        72

    accuracy                           0.99      5018
   macro avg       0.82      0.67      0.72      5018
weighted avg       0.99      0.99      0.99      5018



In [ ]:
TestLLM.test_model(2, "POS", "SRGPT")

[[4930   12]
 [  56   10]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4942
           1       0.45      0.15      0.23        66

    accuracy                           0.99      5008
   macro avg       0.72      0.57      0.61      5008
weighted avg       0.98      0.99      0.98      5008



In [ ]:
TestLLM.test_model(4, "NEG", "SRGPT")

[[4906   32]
 [  49   31]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4938
           1       0.49      0.39      0.43        80

    accuracy                           0.98      5018
   macro avg       0.74      0.69      0.71      5018
weighted avg       0.98      0.98      0.98      5018



In [ ]:
TestLLM.test_model(4, "NEG", "BERTic")

[[4912   26]
 [  28   52]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4938
           1       0.67      0.65      0.66        80

    accuracy                           0.99      5018
   macro avg       0.83      0.82      0.83      5018
weighted avg       0.99      0.99      0.99      5018



In [ ]:
TestLLM.test_model(2, "NEG", "SRGPT")

[[4901   31]
 [  46   30]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4932
           1       0.49      0.39      0.44        76

    accuracy                           0.98      5008
   macro avg       0.74      0.69      0.72      5008
weighted avg       0.98      0.98      0.98      5008



In [ ]:
TestLLM.compare_models(4, "POS", "BERTic", "SRGPT", compare_misclassified= True )

Texts misclassified for class 1 by both models:
 0                      Od velikog značaja ili važnosti.
1                        osoba koja voli ili je voljena
2                 angažovati ili unajmiti za neki posao
3           preparat koji se koristi za čišćenje nečega
4     Ublažavanje patnje; pokazivanje velike dobrote...
5                               Čin ili proces merenja.
6            sposoban za korektno i validno rezonovanje
7             Učiniti svetim pomoću religijskih obreda.
8     Čin ukrašavanja nečega (u nadi da će od toga p...
9                      Postati stabilan ili stabilniji.
10                              Ukazati poverenje kome.
11                        Stanje zrelosti; puni razvoj.
12                                 Ispuniti očekivanja.
13        koji donosi spasenje ili iskupljenje od greha
14    Koji karakteriše životinje za razliku od biljaka.
15                                  biti privlačan kome
16                   Čin kojim se čini neko dobro delo.

In [ ]:
TestLLM.compare_models(4, "NEG", "BERTic", "SRGPT", compare_misclassified= True)

Texts misclassified for class 1 by both models:
 0              Radnik koji je najamljen da obavi posao.
1                 Umanjiti po vrednosti, karakteru itd.
2                      lišiti slobode; držati u zatvoru
3        Koji nije vlik po količini, broju ili stepenu.
4                                Ljudski čin stvaranja.
5     Jako osećanje, usmereno prema nekoj stvarnoj i...
6     Bolest krvi ili narušavanje funkcionisanja krv...
7     Tih neprekidan nerazumljiv zvuk; obično ga pra...
8     (krivično pravo) pravnosnažna,osuđujuća presud...
9               osoba ili firma koja zapošljava radnike
10               Sastavljati od komponenata ili delova.
11                                 Čin prljanja nečega.
12    Pričati na besposlen ili neobavezan način sa e...
13    Nesposobnost osobe da se seti ili uradi ono št...
14      Čin konstruisanja nečega (kao masšinskog dela).
15    Koga karakeriše ili koji pokazuje odbijanje, p...
16    Stanje stvari koje je skoro izvan nečije moguć...

In [ ]:
TestLLM.compare_models(4, "POS", "BERTic", "SRGPT", compare_misclassified= True, compare_other_class=True)

Texts misclassified for class 0 by both models:
 0    koji izaziva iznenađenje, čuđenje ili zadivlje...
1    koji zaslužuje sažaljenje ili podstiče na saža...
2    Onaj koji nema ili ne pokazuje sažaljenje ili ...
3                 Ne pridržavanje moralnim principima.
4                      Ne osecati se dobro ili udobno.
5    Kvalitet nečega što nije adekvatno ili perfektno.
6    Kvalitet nekoga ili nečega što nije važno ili ...
7    Stanje u kome je neko bogat, ima obilno materi...
Name: X, dtype: object
Texts misclassified for class 0 by the first model but not the second:
 138     Odsustvo kvaliteta koji bi činili nešto vredni...
1017                              zlonamerno zadovoljstvo
1024                Znanje i vrednosti koje društvo deli.
2156                      Kvalitet onog ko nije brižljiv.
4737                               nešto što ima vrednost
Name: X, dtype: object
Texts misclassified for class 0 by the second model but not the first:
 225            stanje bola ili 

In [ ]:
TestLLM.compare_models(4, "NEG", "BERTic", "SRGPT",  compare_misclassified= True, compare_other_class=True)

Texts misclassified for class 0 by both models:
 0           nešto što nije sigurno, što je pod sumnjom
1            Koji privremeno nije aktivan, o vulkanima
2                                  Osoba koje ne radi.
3    iznenadni masovni strah i nespokojstvo zbog oč...
4                 Ne pridržavanje moralnim principima.
5      Koji ne predstavlja teškoću, ne iziskuje napor.
Name: X, dtype: object
Texts misclassified for class 0 by the first model but not the second:
 299                                      Čin zagađivanja.
680       koji pobuđuje poštovanje, divljenje ili čuđenje
859                 Naljutiti, posebno nevažnim uzrocima.
1144                         Prekinuti nečije zaposlenje.
2233                                    Učiniti nečistim.
3083           Osoba koja krši morlne ili zakonske norme.
3134                  brutalan, varvarski i divljački čin
3282                                    Čin opstruiranja.
3373                                      Učiniti slabim.
3401

In [ ]:
TestLLM.compare_models(4, "POS", "BERTic", "SRGPT", compare_other_class=True)

Texts correctly classified as class 0 by both models:
 0         Nešto što je manje od celine ljudske tvorevine.
1       Zgrada u kojoj je bar koji ima dozvolu da služ...
2       mehanizam odbrane koji se sastoji u usredsređe...
3                               usoljena i sušena haringa
4       procep na zemljinoj kori (ili površini neke dr...
                              ...                        
4929    u računarstvu, grafički simbol (obično jendost...
4930    Noćni miš iz starog sveta iz roda Apodemus živ...
4931    posuđe sastavljeno od kompletnog seta (srebro ...
4932                     neko ko daje savete o problemima
4933    programske instrukcije zapisane kao ASCII teks...
Name: X, Length: 4934, dtype: object
Texts correctly classified as class 0 by the first model but not the second:
 225            stanje bola ili patnje zbog lošeg zdravlja
459                                   Biti u saglasnosti.
1402    Koji nije u skladu sa metodama ili principima ...
1438              

In [ ]:
TestLLM.compare_models(4, "NEG", "BERTic", "SRGPT", compare_other_class=True)

Texts correctly classified as class 0 by both models:
 0       Prostorno svojstvo: način na koji je nešto sme...
1       Republika u severnoj Evropi; stekla nezavisnos...
2       Vodozemci samo sa jednim, prednjim parom nogu....
3            grupa koralnih ostrva u istočnoj Mikroneziji
4       koji je pisan kurzivnom formom staroegipatskog...
                              ...                        
4941    Vrlo rasprostranjena porodica uglavnom tropsko...
4942    elektronski uređaj koji predstavlja informacij...
4943                             koji može da se redukuje
4944    mesto opremljeno instrumentima za testiranje u...
4945                                   deo štampanog rada
Name: X, Length: 4946, dtype: object
Texts correctly classified as class 0 by the first model but not the second:
 10      briga o razlikovanju dobra i zla ili pravednog...
37           Koji ima veseo karkater, nije sklon brigama.
584     biti u stanju mirovanja; biti u situaciji koja...
787     smear with

In [ ]:
TestLLM.test_model(0, "NEG", "BERTicovo")

[[3963  940]
 [  46    8]]
              precision    recall  f1-score   support

           0       0.99      0.81      0.89      4903
           1       0.01      0.15      0.02        54

    accuracy                           0.80      4957
   macro avg       0.50      0.48      0.45      4957
weighted avg       0.98      0.80      0.88      4957



In [ ]:
TestLLM.test_model(0, "POS", "BERTicovo")

[[3946  974]
 [  31    6]]
              precision    recall  f1-score   support

           0       0.99      0.80      0.89      4920
           1       0.01      0.16      0.01        37

    accuracy                           0.80      4957
   macro avg       0.50      0.48      0.45      4957
weighted avg       0.98      0.80      0.88      4957



In [ ]:
TestLLM.test_model(2, "NEG", "BERTicovo")

[[3968  964]
 [  65   11]]
              precision    recall  f1-score   support

           0       0.98      0.80      0.89      4932
           1       0.01      0.14      0.02        76

    accuracy                           0.79      5008
   macro avg       0.50      0.47      0.45      5008
weighted avg       0.97      0.79      0.87      5008



In [ ]:
TestLLM.test_model(2, "POS", "BERTicovo")

[[3946  996]
 [  55   11]]
              precision    recall  f1-score   support

           0       0.99      0.80      0.88      4942
           1       0.01      0.17      0.02        66

    accuracy                           0.79      5008
   macro avg       0.50      0.48      0.45      5008
weighted avg       0.97      0.79      0.87      5008



In [ ]:
TestLLM.test_model(4, "NEG", "BERTicovo")

[[3969  969]
 [  63   17]]
              precision    recall  f1-score   support

           0       0.98      0.80      0.88      4938
           1       0.02      0.21      0.03        80

    accuracy                           0.79      5018
   macro avg       0.50      0.51      0.46      5018
weighted avg       0.97      0.79      0.87      5018



In [ ]:
TestLLM.test_model(4, "POS", "BERTicovo")

[[3968  978]
 [  57   15]]
              precision    recall  f1-score   support

           0       0.99      0.80      0.88      4946
           1       0.02      0.21      0.03        72

    accuracy                           0.79      5018
   macro avg       0.50      0.51      0.46      5018
weighted avg       0.97      0.79      0.87      5018



In [ ]:
TestLLM.test_model(6, "NEG", "BERTicovo")

[[3993  946]
 [  65   19]]
              precision    recall  f1-score   support

           0       0.98      0.81      0.89      4939
           1       0.02      0.23      0.04        84

    accuracy                           0.80      5023
   macro avg       0.50      0.52      0.46      5023
weighted avg       0.97      0.80      0.87      5023



In [ ]:
TestLLM.test_model(6, "POS", "BERTicovo")

[[3964  986]
 [  56   17]]
              precision    recall  f1-score   support

           0       0.99      0.80      0.88      4950
           1       0.02      0.23      0.03        73

    accuracy                           0.79      5023
   macro avg       0.50      0.52      0.46      5023
weighted avg       0.97      0.79      0.87      5023



In [10]:
TestLLM.test_model(4, "NEG", "SRGPT")

[[4357   69]
 [  42   38]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      4426
           1       0.36      0.47      0.41        80

    accuracy                           0.98      4506
   macro avg       0.67      0.73      0.70      4506
weighted avg       0.98      0.98      0.98      4506

