Iteracija 0, polariter positivan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasa5\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


0


Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Map:   0%|          | 0/11895 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTPOS0 into local empty directory.


Download file pytorch_model.bin:   0%|          | 16.5k/2.88G [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/2.88G [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...


Push attempt 1 failed with error: File SRGPTSENTPOS0\pytorch_model.bin cannot be opened.


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 9d0a210259a9102e02edf406bcd40228742272f4 but expected 9f1122c97acb3f471f5384fed2196934d3100389        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Push attempt 2 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 9d0a210259a9102e02edf406bcd40228742272f4 but expected 9f1122c97acb3f471f5384fed2196934d3100389        
To https://huggingface.co/Tanor/SRGPTSENTPOS0
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS0'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/SRGPTSENTPOS0
   9d0a210..814b67a  main -> main



Max memory allocated by tensors:
6.42 GB


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4920    0]
 [  37    0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4920
           1       0.00      0.00      0.00        37

    accuracy                           0.99      4957
   macro avg       0.50      0.50      0.50      4957
weighted avg       0.99      0.99      0.99      4957



C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
The push command with PID 22576

Iteracija 0, polariter negativan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasa5\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


0


Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Map:   0%|          | 0/11895 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTNEG0 into local empty directory.


Download file pytorch_model.bin:   0%|          | 15.4k/2.88G [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

To https://huggingface.co/Tanor/SRGPTSENTNEG0
   859207f..65b73c2  main -> main

To https://huggingface.co/Tanor/SRGPTSENTNEG0
   65b73c2..3abb7d9  main -> main

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Max memory allocated by tensors:
6.42 GB
[[4882   21]
 [  26   28]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4903
           1       0.57      0.52      0.54        54

    accuracy                           0.99      4957
   macro avg       0.78      0.76      0.77      4957
weighted avg       0.99      0.99      0.99      4957



Iteracija 2, polariter positivan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

0


Map:   0%|          | 0/3005 [00:00<?, ? examples/s]

Map:   0%|          | 0/12018 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTPOS2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.00k/2.88G [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/2.88G [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Several commits (2) will be pushed upstream.
The progress bars may b

Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 88a0ce039816e3b1751dde01ebb77991d2405bb8 but expected 2ea55bbd70dce244ab0d0ee1a3d6966919309251        
To https://huggingface.co/Tanor/SRGPTSENTPOS2
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS2'

Error pushing update to the model card. Please read logs and retry.
$remote: error: cannot lock ref 'refs/heads/main': is at 88a0ce039816e3b1751dde01ebb77991d2405bb8 but expected 2ea55bbd70dce244ab0d0ee1a3d6966919309251        
To https://huggingface.co/Tanor/SRGPTSENTPOS2
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/SRGPTSENTPOS2'

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Max memory allocated by tensors:
6.42 GB
[[4942    0]
 [  66    0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4942
           1       0.00      0.00      0.00        66

    accuracy                           0.99      5008
   macro avg       0.49      0.50      0.50      5008
weighted avg       0.97      0.99      0.98      5008



C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Iteracija 2, polariter negativan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

0


Map:   0%|          | 0/3005 [00:00<?, ? examples/s]

Map:   0%|          | 0/12018 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTNEG2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 16.5k/2.88G [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/2.88G [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\check

Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

To https://huggingface.co/Tanor/SRGPTSENTNEG2
   c85e5e0..06b4de3  main -> main

To https://huggingface.co/Tanor/SRGPTSENTNEG2
   06b4de3..77cf0b9  main -> main

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Max memory allocated by tensors:
6.42 GB
[[4901   31]
 [  46   30]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4932
           1       0.49      0.39      0.44        76

    accuracy                           0.98      5008
   macro avg       0.74      0.69      0.72      5008
weighted avg       0.98      0.98      0.98      5008



Iteracija 4, polariter positivan, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

0


Map:   0%|          | 0/3011 [00:00<?, ? examples/s]

Map:   0%|          | 0/12041 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/SRGPTSENTPOS4 into local empty directory.


Download file pytorch_model.bin:   0%|          | 12.5k/2.88G [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/2.88G [00:00<?, ?B/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\check

Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

To https://huggingface.co/Tanor/SRGPTSENTPOS4
   0e9154d..c1de309  main -> main

To https://huggingface.co/Tanor/SRGPTSENTPOS4
   c1de309..9ba17c4  main -> main

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Max memory allocated by tensors:
6.42 GB
[[4921   25]
 [  54   18]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4946
           1       0.42      0.25      0.31        72

    accuracy                           0.98      5018
   macro avg       0.70      0.62      0.65      5018
weighted avg       0.98      0.98      0.98      5018



Iteracija 4, polariter neg, epohe 10, evalicinong metod f1, zaustvlja ranije

In [1]:
%run trainSRGPT.py

0


Map:   0%|          | 0/3011 [00:00<?, ? examples/s]

Map:   0%|          | 0/12041 [00:00<?, ? examples/s]

C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\SRGPTSENTNEG4 is already a clone of https://huggingface.co/Tanor/SRGPTSENTNEG4. Make sure you pull the latest changes with `repo.git_pull()`.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Several commits (3) will be pushed upstream.
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda3\envs\ML\Lib\site-packages\torch\utils\checkpoint.py:426: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\ProgramData\anaconda

Push attempt 1 failed with error: File SRGPTSENTNEG4\pytorch_model.bin cannot be opened.


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file pytorch_model.bin:   0%|          | 1.00/2.88G [00:00<?, ?B/s]

To https://huggingface.co/Tanor/SRGPTSENTNEG4
   f733e64..76d461f  main -> main

To https://huggingface.co/Tanor/SRGPTSENTNEG4
   76d461f..1da5ae3  main -> main



Max memory allocated by tensors:
6.42 GB


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4906   32]
 [  49   31]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4938
           1       0.49      0.39      0.43        80

    accuracy                           0.98      5018
   macro avg       0.74      0.69      0.71      5018
weighted avg       0.98      0.98      0.98      5018

