# Fine-Tuning and Performance Evaluation of BERT Models for Sentiment Classification with Early Stopping

In this Jupyter notebook, we delve into the crucial steps of our Natural Language Processing (NLP) project - fine-tuning our preprocessed BERT models on the Serbian Wordnet training data, and assessing their performance. 

Our primary objective is to adapt BERT models to effectively classify sentiments, leveraging a semi-automated, iterative approach that uses seed words and expands them based on their relationships in WordNet. 

The performance evaluation metrics are instrumental in assessing the success of our fine-tuning process. We will analyze these metrics in two ways:

1. **In-notebook Review:** For an immediate performance evaluation, we will print the confusion matrix and classification reports within this notebook.

2. **Persistent Reports:** We'll create a lasting record of our results by storing these metrics in a separate 'reports' folder. This approach facilitates progress trackingover time, and enables comparisons among different models and fine-tuning iterations.

Keep in mind that the fine-tuning and evaluation processes are iterative. Based on our results and insights, we may need to adjust our strategies and fine-tune our models 
ifferently.

Throughout this notebook, we will go through:

1. **Model Training:** Execution of Python scripts for fine-tuning our BERT models on the training set.
2. **Model Testing:** Performance evaluation of the newly fine-tuned models on our test data.
3. **Results Analysis:** Examination, interpretation, and storage of the confusion matrices and classifIn our previous work, we fine-tuned our BERT models for sentiment classification on the Serbian Wordnet training data. However, the models appeared to be overfitting. Overfitting is a common problem in machine learning where a model learns the training data too well, essentially memorizing it, rather than generalizing from it. This means that it performs poorly on unseen data, which is a big problem if we want our models to be applicable to real-world data.

To overcome this issue, we're going to introduce early stopping in this notebook. Early stopping is a method used to prevent overfitting by ending the training process before the learner passes a certain point of over-specialization, i.e., before the model starts to overfit.

We'll fine-tune our BERT models again, but this time, we'll include an early stopping line in our trainer call. Then, we'll evaluate the performance of these newly fine-tuned models and compare the results to the ones from the previous notebook. Our aim is to obtain models that generalize better and thus, perform better on unseen data.
!
Let's get started!


### Importing Required Modules

In this initial code cell, we import the necessary modules that contain functions for training and testing our BERT models. The modules imported are:

1. **`trainBERTovo`:** This module contains the `train_model` and `test_model` functions for handling the training and testing processes respectively. The BERT model used in this module is the "Jerteh" model, which is pre-trained exclusively on the Serbian language using a RoBERTa architecture. It is tailored to deal with the specificities of the Serbian language, managing everything from data preprocessing to model training, testing, and memory management for GPU use.

2. **`trainBERTic`:** Similar to `trainBERTovo`, this module also contains `train_model` and `test_model` functions. However, the BERT model used in this module is the "Classla" model, which is based on the ELECTRA model and is multilingual, including support for Serbian among other regional languages.

By encapsulating the training and testing processes within these modules, we maintain a clean and streamlined notebook. This allows us to focus on the implementation, results interpretation, and performance evaluation of the 
erstand.


In [1]:
import trainBERTovo
import trainBERTic

## Iteration 0 - Training and Testing
In this section, we use the data from the 0th iteration of the semi-automatic iterative algorithm for both Positive and Negative sentiment classification to train and test our BERT models

s.


In [ ]:
trainBERTic.train_model(0, "POS", eval="f1", epochs =32)

In [3]:
trainBERTic.test_model(0, "POS")

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4387   21]
 [   8   29]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4408
           1       0.58      0.78      0.67        37

    accuracy                           0.99      4445
   macro avg       0.79      0.89      0.83      4445
weighted avg       0.99      0.99      0.99      4445



In [4]:
trainBERTic.test_model_local(0, "POS")

[[4387   21]
 [   8   29]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4408
           1       0.58      0.78      0.67        37

    accuracy                           0.99      4445
   macro avg       0.79      0.89      0.83      4445
weighted avg       0.99      0.99      0.99      4445



In [2]:
trainBERTic.upload_local_model_to_hub(0, "POS")

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

In [ ]:
trainBERTic.train_model(0, "NEG", eval="f1", epochs =32)

In [5]:
trainBERTic.upload_local_model_to_hub(0, "NEG")

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

In [6]:
trainBERTic.test_model(0, "NEG")

[[4381   10]
 [  17   37]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4391
           1       0.79      0.69      0.73        54

    accuracy                           0.99      4445
   macro avg       0.89      0.84      0.86      4445
weighted avg       0.99      0.99      0.99      4445



In [ ]:
trainBERTovo.train_model(0, "POS", eval="f1", epochs = 32)

In [4]:
trainBERTovo.test_model_local(0, "POS")

[[4404    4]
 [  28    9]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4408
           1       0.69      0.24      0.36        37

    accuracy                           0.99      4445
   macro avg       0.84      0.62      0.68      4445
weighted avg       0.99      0.99      0.99      4445



In [5]:
trainBERTovo.upload_local_model_to_hub(0, "POS")

pytorch_model.bin:   0%|          | 0.00/574M [00:00<?, ?B/s]

In [6]:
trainBERTovo.test_model(0, "POS")

[[4404    4]
 [  28    9]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4408
           1       0.69      0.24      0.36        37

    accuracy                           0.99      4445
   macro avg       0.84      0.62      0.68      4445
weighted avg       0.99      0.99      0.99      4445



In [8]:
trainBERTovo.train_model(0, "NEG", eval="f1", epochs =32)

Map:   0%|          | 0/1334 [00:00<?, ? examples/s]

Map:   0%|          | 0/11998 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTovoSENTNEG0 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.00k/548M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTovoSENTNEG0
   70ea6ec..97b839a  main -> main



Push attempt 1 failed with error: Failed to remove file C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\objects\c8\66\c866567ef57aded01967f3c4a7d499e33267f259628b76e0e08cca07227f7aa6: remove C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\objects\c8\66\c866567ef57aded01967f3c4a7d499e33267f259628b76e0e08cca07227f7aa6: The process cannot access the file because it is being used by another process.


Errors logged to 'C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\logs\20230908T155054.856025.log'.
Use `git lfs logs last` to view the log.
Prune failed, see errors above



To https://huggingface.co/Tanor/BERTovoSENTNEG0
   97b839a..efe818d  main -> main

Error pushing update to the model card. Please read logs and retry.
$Failed to remove file C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\objects\c8\66\c866567ef57aded01967f3c4a7d499e33267f259628b76e0e08cca07227f7aa6: remove C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\objects\c8\66\c866567ef57aded01967f3c4a7d499e33267f259628b76e0e08cca07227f7aa6: The process cannot access the file because it is being used by another process.


Errors logged to 'C:\Users\sasa5\OneDrive\Documents\GitHub\SerbianSentiWordNET\BERTovoSENTNEG0\.git\lfs\logs\20230908T155116.8386592.log'.
Use `git lfs logs last` to view the log.
Prune failed, see errors above



Max memory allocated by tensors- before:
    2.56 GB
Max memory allocated by tensors- after:
    2.56 GB


In [9]:
trainBERTovo.test_model_local(0, "NEG")

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [10]:
trainBERTovo.upload_local_model_to_hub(0, "NEG")

pytorch_model.bin:   0%|          | 0.00/574M [00:00<?, ?B/s]

In [11]:
trainBERTovo.test_model(0, "NEG")

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

## Iteration 2 - Training and Testing
In this section, we use the data from the 2nd iteration of the semi-automatic iterative algorithm for both Positive and Negative sentiment classification to train and test our BERT models.

y.


In [2]:
trainBERTic.train_model(2, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1349 [00:00<?, ? examples/s]

Map:   0%|          | 0/12137 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTPOS2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 15.4k/422M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 2b9956d1fff86f40d22e3e58e393285ec722fadb but expected 8834de682363fb5b17aca6c5767779df7f644f77        
To https://huggingface.co/Tanor/BERTicSENTPOS2
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS2'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 2b9956d1fff86f40d22e3e58e393285ec722fadb but expected 8834de682363fb5b17aca6c5767779df7f644f77        
To https://huggingface.co/Tanor/BERTicSENTPOS2
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS2'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicSENTPOS2
   2b9956d..8c933e5  main -> main



Max memory allocated by tensors- before:
    2.11 GB
Max memory allocated by tensors- after:
    2.11 GB


In [3]:
trainBERTic.test_model_local(2, "POS")

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[[4422    8]
 [  42   24]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4430
           1       0.75      0.36      0.49        66

    accuracy                           0.99      4496
   macro avg       0.87      0.68      0.74      4496
weighted avg       0.99      0.99      0.99      4496



In [4]:
trainBERTic.upload_local_model_to_hub(2, "POS")

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

In [5]:
trainBERTic.test_model(2, "POS")

[[4422    8]
 [  42   24]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4430
           1       0.75      0.36      0.49        66

    accuracy                           0.99      4496
   macro avg       0.87      0.68      0.74      4496
weighted avg       0.99      0.99      0.99      4496



In [6]:
trainBERTic.train_model(2, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1349 [00:00<?, ? examples/s]

Map:   0%|          | 0/12137 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTNEG2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.15k/422M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTicSENTNEG2
   96408c5..3f06d13  main -> main

To https://huggingface.co/Tanor/BERTicSENTNEG2
   3f06d13..53a89aa  main -> main



Max memory allocated by tensors- before:
    2.21 GB
Max memory allocated by tensors- after:
    2.21 GB


In [7]:
trainBERTic.test_model_local(2, "NEG")

[[4389   31]
 [  18   58]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      4420
           1       0.65      0.76      0.70        76

    accuracy                           0.99      4496
   macro avg       0.82      0.88      0.85      4496
weighted avg       0.99      0.99      0.99      4496



In [8]:
trainBERTic.upload_local_model_to_hub(2, "NEG")

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

In [9]:
trainBERTic.test_model(2, "NEG")

[[4389   31]
 [  18   58]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      4420
           1       0.65      0.76      0.70        76

    accuracy                           0.99      4496
   macro avg       0.82      0.88      0.85      4496
weighted avg       0.99      0.99      0.99      4496



In [10]:
trainBERTovo.train_model(2, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1349 [00:00<?, ? examples/s]

Map:   0%|          | 0/12137 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTovoSENTPOS2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.00k/548M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTovoSENTPOS2
   089ee56..45bbca8  main -> main

To https://huggingface.co/Tanor/BERTovoSENTPOS2
   45bbca8..728c098  main -> main



Max memory allocated by tensors- before:
    2.35 GB
Max memory allocated by tensors- after:
    2.35 GB


In [ ]:
trainBERTovo.test_model_local(2, "POS")

In [4]:
trainBERTovo.upload_local_model_to_hub(2, "POS")

pytorch_model.bin:   0%|          | 0.00/574M [00:00<?, ?B/s]

In [ ]:
trainBERTovo.test_model(2, "POS")

In [12]:
trainBERTovo.train_model(2, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1349 [00:00<?, ? examples/s]

Map:   0%|          | 0/12137 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTovoSENTNEG2 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.74k/548M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTovoSENTNEG2
   82162e3..9531731  main -> main

To https://huggingface.co/Tanor/BERTovoSENTNEG2
   9531731..8354019  main -> main



Max memory allocated by tensors- before:
    2.57 GB
Max memory allocated by tensors- after:
    2.57 GB


In [2]:
trainBERTovo.test_model_local(2, "NEG")

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [3]:
trainBERTovo.upload_local_model_to_hub(2, "NEG")

pytorch_model.bin:   0%|          | 0.00/574M [00:00<?, ?B/s]

In [ ]:
trainBERTovo.test_model(2, "NEG")

## Iteration 4 - Training and Testing
In this section, we use the data from the 4th iteration of the semi-automatic iterative algorithm for both Positive and Negative sentiment classification to train and test our BERT models.


In [5]:
trainBERTic.train_model(4, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1352 [00:00<?, ? examples/s]

Map:   0%|          | 0/12163 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTPOS4 into local empty directory.


Download file pytorch_model.bin:   0%|          | 12.5k/422M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 97ad6d3f1ebe44b5e987ef9056430dccab9b2b6a but expected 181f2dc948babce34df73ca3529b4edfa83b8ba9        
To https://huggingface.co/Tanor/BERTicSENTPOS4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS4'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 97ad6d3f1ebe44b5e987ef9056430dccab9b2b6a but expected 181f2dc948babce34df73ca3529b4edfa83b8ba9        
To https://huggingface.co/Tanor/BERTicSENTPOS4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS4'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicSENTPOS4
   97ad6d3..7ff98da  main -> main



Max memory allocated by tensors- before:
    2.11 GB
Max memory allocated by tensors- after:
    2.11 GB


In [6]:
trainBERTic.test_model(4, "POS")

[[4423   11]
 [  44   28]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4434
           1       0.72      0.39      0.50        72

    accuracy                           0.99      4506
   macro avg       0.85      0.69      0.75      4506
weighted avg       0.99      0.99      0.99      4506



In [7]:
trainBERTic.train_model(4, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1352 [00:00<?, ? examples/s]

Map:   0%|          | 0/12163 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTNEG4 into local empty directory.


Download file pytorch_model.bin:   0%|          | 7.40k/422M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Download file model.safetensors:   0%|          | 18.4k/422M [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at dc0885c82e81778e1846bced40c787ee5d05901f but expected 57c4f5e15ab03483f1a2b6b118339de81014595d        
To https://huggingface.co/Tanor/BERTicSENTNEG4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTNEG4'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at dc0885c82e81778e1846bced40c787ee5d05901f but expected 57c4f5e15ab03483f1a2b6b118339de81014595d        
To https://huggingface.co/Tanor/BERTicSENTNEG4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTNEG4'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicSENTNEG4
   dc0885c..9d3dfbc  main -> main



Max memory allocated by tensors- before:
    2.12 GB
Max memory allocated by tensors- after:
    2.12 GB


In [8]:
trainBERTic.test_model(4, "NEG")

[[4413   13]
 [  20   60]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4426
           1       0.82      0.75      0.78        80

    accuracy                           0.99      4506
   macro avg       0.91      0.87      0.89      4506
weighted avg       0.99      0.99      0.99      4506



In [13]:
trainBERTovo.train_model(4, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1352 [00:00<?, ? examples/s]

Map:   0%|          | 0/12163 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicovoSENTPOS4 into local empty directory.


Download file pytorch_model.bin:   0%|          | 16.5k/548M [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/548M [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at f766bfabfc289276ba9ef36f0adda387e4e8c1a9 but expected b5f87af2c4e447e0dc384ef0246577eabf4c407f        
To https://huggingface.co/Tanor/BERTicovoSENTPOS4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicovoSENTPOS4'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at f766bfabfc289276ba9ef36f0adda387e4e8c1a9 but expected b5f87af2c4e447e0dc384ef0246577eabf4c407f        
To https://huggingface.co/Tanor/BERTicovoSENTPOS4
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicovoSENTPOS4'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicovoSENTPOS4
   f766bfa..237b42e  main -> main



Max memory allocated by tensors- before:
    2.35 GB
Max memory allocated by tensors- after:
    2.35 GB


In [ ]:
trainBERTovo.test_model(4, "POS")

In [14]:
trainBERTovo.train_model(4, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1352 [00:00<?, ? examples/s]

Map:   0%|          | 0/12163 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicovoSENTNEG4 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.74k/548M [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/548M [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTicovoSENTNEG4
   d899600..185409e  main -> main

To https://huggingface.co/Tanor/BERTicovoSENTNEG4
   185409e..97b63e9  main -> main



Max memory allocated by tensors- before:
    2.35 GB
Max memory allocated by tensors- after:
    2.35 GB


In [ ]:
trainBERTovo.test_model(4, "NEG")

## Iteration 6 - Training and Testing
In this section, we use the data from the 6th iteration of the semi-automatic iterative algorithm for both Positive and Negative sentiment classification to train and test our BERT models.


In [9]:
trainBERTic.train_model(6, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1354 [00:00<?, ? examples/s]

Map:   0%|          | 0/12177 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTPOS6 into local empty directory.


Download file pytorch_model.bin:   0%|          | 3.37k/422M [00:00<?, ?B/s]

Download file training_args.bin: 100%|##########| 3.87k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 294dad06a5e474989522977ed0d7d493b6422364 but expected 7e95af1bf26b2978d60bb0c7b80813800bbbb0f4        
To https://huggingface.co/Tanor/BERTicSENTPOS6
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS6'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 294dad06a5e474989522977ed0d7d493b6422364 but expected 7e95af1bf26b2978d60bb0c7b80813800bbbb0f4        
To https://huggingface.co/Tanor/BERTicSENTPOS6
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTPOS6'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicSENTPOS6
   294dad0..a5ee6a7  main -> main



Max memory allocated by tensors- before:
    2.21 GB
Max memory allocated by tensors- after:
    2.21 GB


In [10]:
trainBERTic.test_model(6, "POS")

[[4432    6]
 [  49   24]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4438
           1       0.80      0.33      0.47        73

    accuracy                           0.99      4511
   macro avg       0.89      0.66      0.73      4511
weighted avg       0.99      0.99      0.99      4511



In [11]:
trainBERTic.train_model(6, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1354 [00:00<?, ? examples/s]

Map:   0%|          | 0/12177 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicSENTNEG6 into local empty directory.


Download file pytorch_model.bin:   0%|          | 8.74k/422M [00:00<?, ?B/s]

Download file training_args.bin:  81%|########  | 3.12k/3.87k [00:00<?, ?B/s]

Clean file training_args.bin:  26%|##5       | 1.00k/3.87k [00:00<?, ?B/s]

You're using a ElectraTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/422M [00:00<?, ?B/s]

remote: error: cannot lock ref 'refs/heads/main': is at 4b0bc2cc22e477cbc102da15339f92da73233a3c but expected df5d83c61b56ef9d2656c5daa4495f7ff21d8cc8        
To https://huggingface.co/Tanor/BERTicSENTNEG6
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTNEG6'



Push attempt 1 failed with error: remote: error: cannot lock ref 'refs/heads/main': is at 4b0bc2cc22e477cbc102da15339f92da73233a3c but expected df5d83c61b56ef9d2656c5daa4495f7ff21d8cc8        
To https://huggingface.co/Tanor/BERTicSENTNEG6
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/Tanor/BERTicSENTNEG6'



Several commits (2) will be pushed upstream.
The progress bars may be unreliable.
To https://huggingface.co/Tanor/BERTicSENTNEG6
   4b0bc2c..06a0c66  main -> main



Max memory allocated by tensors- before:
    2.21 GB
Max memory allocated by tensors- after:
    2.21 GB


In [12]:
trainBERTic.test_model(6, "NEG")

[[4398   29]
 [  23   61]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4427
           1       0.68      0.73      0.70        84

    accuracy                           0.99      4511
   macro avg       0.84      0.86      0.85      4511
weighted avg       0.99      0.99      0.99      4511



In [15]:
trainBERTovo.train_model(6, "POS", eval="f1", epochs = 32)

Map:   0%|          | 0/1354 [00:00<?, ? examples/s]

Map:   0%|          | 0/12177 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicovoSENTPOS6 into local empty directory.


Download file pytorch_model.bin:   0%|          | 7.40k/548M [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/548M [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTicovoSENTPOS6
   20bae3a..d37d603  main -> main

To https://huggingface.co/Tanor/BERTicovoSENTPOS6
   d37d603..bb4ea6b  main -> main



Max memory allocated by tensors- before:
    2.57 GB
Max memory allocated by tensors- after:
    2.57 GB


In [17]:
trainBERTovo.test_model(6, "POS")

[[4437    1]
 [  63   10]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4438
           1       0.91      0.14      0.24        73

    accuracy                           0.99      4511
   macro avg       0.95      0.57      0.62      4511
weighted avg       0.98      0.99      0.98      4511



In [16]:
trainBERTovo.train_model(6, "NEG", eval="f1", epochs = 32)

Map:   0%|          | 0/1354 [00:00<?, ? examples/s]

Map:   0%|          | 0/12177 [00:00<?, ? examples/s]

Cloning https://huggingface.co/Tanor/BERTicovoSENTNEG6 into local empty directory.


Download file pytorch_model.bin:   0%|          | 16.4k/548M [00:00<?, ?B/s]

Clean file pytorch_model.bin:   0%|          | 1.00k/548M [00:00<?, ?B/s]

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\torch\utils\checkpoint.py:428: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
c:\Users\sasa5\anaconda3\envs\hugFace\Lib\site-packages\to

Upload file pytorch_model.bin:   0%|          | 1.00/548M [00:00<?, ?B/s]

To https://huggingface.co/Tanor/BERTicovoSENTNEG6
   4e715cd..32c0bb5  main -> main

To https://huggingface.co/Tanor/BERTicovoSENTNEG6
   32c0bb5..88a1045  main -> main



Max memory allocated by tensors- before:
    2.57 GB
Max memory allocated by tensors- after:
    2.57 GB


In [18]:
trainBERTovo.test_model(6, "NEG")

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)